#pragma once

#include "objectir_runtime.hpp"
#include "fob_loader.hpp"
#include <nlohmann/json.hpp>
#include <fstream>
#include <sstream>

namespace ObjectIR
{

    using json = nlohmann::json;

    // ============================================================================
    // IR File Loader - Deserialize IR modules from JSON or FOB format
    // ============================================================================

    /// Loads ObjectIR modules from JSON format (as generated by C# builder) or FOB binary format
    class OBJECTIR_API IRLoader
    {
    public:
        /// Load a module from a file path (auto-detects JSON or FOB format)
        static std::shared_ptr<VirtualMachine> LoadFromFile(const std::string &filePath);

        /// Load a module from a JSON string
        static std::shared_ptr<VirtualMachine> LoadFromString(const std::string &jsonStr);

        /// Load a module from FOB binary data
        static std::shared_ptr<VirtualMachine> LoadFromFOBData(const std::vector<uint8_t> &data);

        /// Detect file format by reading the first few bytes
        static bool IsFOBFormat(const std::string &filePath);

    private:
        IRLoader() = default;

        /// Parse JSON and create VirtualMachine with all types and methods
        static std::shared_ptr<VirtualMachine> ParseModule(const json &moduleJson);

        /// Load all type definitions from JSON
        static void LoadTypes(std::shared_ptr<VirtualMachine> vm, const json &typesArray);

        /// Load a single type definition
        static void LoadTypeDefinition(
            std::shared_ptr<VirtualMachine> vm,
            const json &typeJson);

        /// Load a class definition
        static ClassRef LoadClass(
            std::shared_ptr<VirtualMachine> vm,
            const json &classJson);

        /// Load an interface definition
        static void LoadInterface(
            std::shared_ptr<VirtualMachine> vm,
            const json &interfaceJson);

        /// Load a struct definition
        static void LoadStruct(
            std::shared_ptr<VirtualMachine> vm,
            const json &structJson);

        /// Load method definitions for a class
        static void LoadMethods(
            ClassRef classRef,
            const json &methodsArray,
            std::shared_ptr<VirtualMachine> vm);

        /// Load fields for a class
        static void LoadFields(
            ClassRef classRef,
            const json &fieldsArray,
            std::shared_ptr<VirtualMachine> vm);

        /// Parse type reference from string (e.g., "int32", "MyClass")
        static TypeReference ParseTypeReference(
            std::shared_ptr<VirtualMachine> vm,
            const std::string &typeStr);

        /// Get fully qualified type name from JSON
        static std::string GetFQTypeName(const std::string &name, const std::string &ns);
    };

} // namespace ObjectIR
